### ISSUE TITLE
FortiGate-HA-Dual-Load-Balancer  failed to deployed vnet reference pb

### ISSUE THREAD

**Issue by thomnico** [fortinetsolutions/Azure-Templates#1]
When trying to deploy using az : 

Deployment failed. {
  "error": {
    "code": "InvalidResourceReference",
    "message": "Resource /subscriptions/da243d46-282e-4eec-ab71-7c33208b341a/resourceGroups//providers/Microsoft.Network/virtualNetworks/FORTIGATEPROTECTEDVNET referenced by resource /subscriptions/da243d46-282e-4eec-ab71-7c33208b341a/resourceGroups/experience.Fortinet/providers/Microsoft.Network/loadBalancers/fgtAZ-InternalLoadBalancer was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.",
    "details": [
      {
        "code": "NotFound",
        "message": "Resource /subscriptions/da243d46-282e-4eec-ab71-7c33208b341a/resourceGroups//providers/Microsoft.Network/virtualNetworks/FORTIGATEPROTECTEDVNET not found."
      }
    ]
  }
}

Looks like a bad reference/typo ..

**Comment by thomnico** [comment]
Answering myself :
If setting 	 "vnetResourceGroup":  parameter then this error disappear .. (should used the default ressourceGroup if not specified)

**Comment by ciamciaramciam** [comment]
Has anybody seen this error?
Deployment template validation failed: 'The resource 'Microsoft.Network/routeTables/-MyGatewayRouteTable' at line '1' and column '7984' is defined multiple times in a template. Please see https://aka.ms/arm-template/#resources for usage details.'. (Code: InvalidTemplate)

**Comment by fortinetclouddev** [comment]
Yes, that error indicates that you haven't completed the subnet name parameters.  All parameters are required to get this template to deploy properly.

**Comment by ciamciaramciam** [comment]
Perfect, it's working now. Thank you. Some optional fields are actually mandatory.
