### ISSUE TITLE
FortiGate-HA-Dual-Load-Balancer-4NIC Template can not be deployed

### ISSUE THREAD

**Issue by TilmanBu** [fortinetsolutions/Azure-Templates#2]
Hello,

we try to deploy the template atm (FortiGate-HA-Dual-Load-Balancer-4NIC) 

But at the end we always facing the error shown in the screenshot.

![unexpected](https://user-images.githubusercontent.com/34909212/34404745-b81a2f38-ebaf-11e7-9d38-38508d2a9d7f.png)

any suggestions? Line 7 in the code looks fine for us.

Thank you for your Help.

Kind regards.

**Comment by fortinetclouddev** [comment]
There are several errors in the parameters.  Address and subnet prefixes must be in CIDR notation - example 10.0.1.0/24
