### ISSUE TITLE
missing SNAT on Azure STD LB

### ISSUE THREAD

**Issue by shayshahak-zz** [fortinetsolutions/Azure-Templates#3]
the FW members can't reach the public internet.
something is missing in the deployment.
without adding a public ip directly to the FW members there's no internet connectivity.

**Comment by fortinetclouddev** [comment]
Thanks Shay!  Turned out, the standard Azure load balancer requires inbound load balancer rules before it will perform outbound SNAT... To get around this, sample TCP and UDP rules have been added to the public load balancer in the current template.

**Comment by shayshahak-zz** [comment]
adding the dummy inbound rule in order to enable outbound SNAT is not needed anymore.
see here:
https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-rules-overview
