### ISSUE TITLE
Missing a UDP load balancing rule on the public load balancer

### ISSUE THREAD

**Issue by nicolapom** [fortinetsolutions/Azure-Templates#4]
Hello
I had to create a UDP load balancing rule on the public load balancer with Direct Server Return disable. This is required for the fortinet to be able to initiate UDP traffic towards the internet.
Otherwise it can not contact the Fortiguard servers (web filter license will not activate) nor the NTP servers.
This is due to the usage of Standard SKU load balancers and described here 👍 https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#preallocatedports

if you can integrate this in the template that would be great

**Comment by willih** [comment]
Thanks nicolapom, saved me some troubleshooting.

**Comment by fortinetclouddev** [comment]
Thanks.  This has been added to the template now.

**Comment by shayshahak-zz** [comment]
adding the dummy inbound rule in order to enable outbound SNAT is not needed anymore.
see here:
https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-rules-overview
